### PR TITLE
feat: update pgwire to 0.19

### PR DESCRIPTION
**Pull request by sunng87**
## Rationale

pgwire author here. This patch updates pgwire to 0.19 which contains compatibility fixes and API improvements.

## Test Plan
Pass CI

### CODE REVIEW

**Comment by ShiKaiWi** [comment]
The style check failure is caused by upgrade of `chrono`. I guess we can only upgrade `pgwire`. Let me fix it.

**Comment by sunng87** [comment]
By the way, I'm having trouble with compiling librocksdb-sys on my archlinux:

```
  --- stderr
     Entering             /home/sunng/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb/third-party/gtest-1.8.1/fused-src/gtest
     Called from: [1]	/home/sunng/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb/CMakeLists.txt
     Returning to         /home/sunng/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb
     Called from: [1]	/home/sunng/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb/CMakeLists.txt
     Entering             /home/sunng/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb/tools
     Called from: [1]	/home/sunng/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb/CMakeLists.txt
     Returning to         /home/sunng/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb
     Called from: [1]	/home/sunng/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb/CMakeLists.txt
  /home/sunng/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb/db/db_impl/db_impl.cc: In member function ‘virtual rocksdb::Status rocksdb::DBImpl::FlushWAL(bool)’:
  /home/sunng/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb/db/db_impl/db_impl.cc:1349:23: error: redundant move in return statement [-Werror=redundant-move]
   1349 |       return std::move(io_s);
        |              ~~~~~~~~~^~~~~~
  /home/sunng/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb/db/db_impl/db_impl.cc:1349:23: note: remove ‘std::move’ call
  /home/sunng/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb/db/db_impl/db_impl.cc:1353:23: error: redundant move in return statement [-Werror=redundant-move]
   1353 |       return std::move(io_s);
        |              ~~~~~~~~~^~~~~~
  /home/sunng/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb/db/db_impl/db_impl.cc:1353:23: note: remove ‘std::move’ call
  /home/sunng/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb/db/db_impl/db_impl.cc: In member function ‘virtual rocksdb::Status rocksdb::DBImpl::LockWAL()’:
  /home/sunng/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb/db/db_impl/db_impl.cc:1470:19: error: redundant move in return statement [-Werror=redundant-move]
   1470 |   return std::move(status);
        |          ~~~~~~~~~^~~~~~~~
  /home/sunng/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/f04f4dd/librocksdb_sys/rocksdb/db/db_impl/db_impl.cc:1470:19: note: remove ‘std::move’ call
  cc1plus: all warnings being treated as errors
  make[3]: *** [CMakeFiles/rocksdb.dir/build.make:555: CMakeFiles/rocksdb.dir/db/db_impl/db_impl.cc.o] Error 1
  make[3]: *** Waiting for unfinished jobs....
  make[2]: *** [CMakeFiles/Makefile2:142: CMakeFiles/rocksdb.dir/all] Error 2
  make[1]: *** [CMakeFiles/Makefile2:149: CMakeFiles/rocksdb.dir/rule] Error 2
  make: *** [Makefile:172: rocksdb] Error 2
  thread 'main' panicked at /home/sunng/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 2

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Is librocksdb-sys a required dependency? I wonder if there is any way to skip it.

**Comment by jiacai2050** [comment]
> Is librocksdb-sys a required dependency?

```
make build-wal-table-kv
```
It will build without rocksdb.

**Comment by ShiKaiWi** [comment]
> The style check failure is caused by upgrade of `chrono`. I guess we can only upgrade `pgwire`. Let me fix it.

It seems impossible to only upgrade `pgwire`. The deprecated method is replaced with the right one.

**Comment by ShiKaiWi** [comment]
@sunng87 The CI has passed. Thanks.

**Review by ShiKaiWi — APPROVED** [review]
LGTM

**Pull request merged**
