### PR TITLE
feat: optimize minor issues

### PR DESCRIPTION
**Pull request by zealchen**
## Rationale
Related with https://github.com/apache/incubator-horaedb/issues/1466, fix minor issues.

## Detailed Changes
1. Make execution_props an arguments to logical2physical.
2. Make scan_batch_size NonZeroUsize

## Test Plan
Manual test

### CODE REVIEW

**Comment by jiacai2050** [comment]
Would you mind also remove following TODOs, since they are stale.
```
 // Only `Eq` is supported now. 

 // TODO: subscriber.with(layer1) has the different type with 

```

**Review by jiacai2050 — DISMISSED** [review]
LGTM

**Review by tanruixiang — APPROVED** [review]
LGTM

**Review by jiacai2050 — APPROVED** [review]
LGTM

**Pull request merged**
