### PR TITLE
chore: add slack link

### PR DESCRIPTION
**Pull request by tanruixiang**
## Rationale
add slack link 
## Test Plan
no need

### CODE REVIEW

**Comment by tanruixiang** [comment]
@jiacai2050  I have invited you to slack, please check your email and give the feedback here.

**Comment by jiacai2050** [comment]
Joined

**Comment by ShiKaiWi** [comment]
@tanruixiang Conflicts need resolving.

**Review by jiacai2050 — APPROVED** [review]
LGTM

**Pull request merged**
